import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#eaddff",
        "tertiary-container": "#a44100",
        "on-secondary-fixed-variant": "#5a00c6",
        "tertiary": "#ffb695",
        "error-container": "#93000a",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#303034",
        "secondary": "#d2bbff",
        "primary-fixed": "#e2dfff",
        "on-secondary": "#3f008e",
        "background": "#131317",
        "on-secondary-fixed": "#25005a",
        "on-secondary-container": "#c9aeff",
        "inverse-surface": "#e4e1e7",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-surface": "#e4e1e7",
        "on-tertiary": "#571f00",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container-high": "#2a292e",
        "on-primary": "#1d00a5",
        "on-primary-container": "#dad7ff",
        "secondary-fixed-dim": "#d2bbff",
        "surface-variant": "#353439",
        "inverse-primary": "#4d44e3",
        "secondary-container": "#6001d1",
        "on-error-container": "#ffdad6",
        "surface-tint": "#c3c0ff",
        "surface": "#131317",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container": "#1f1f23",
        "on-tertiary-container": "#ffd2be",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-highest": "#353439",
        "on-background": "#e4e1e7",
        "surface-container-low": "#1b1b1f",
        "surface-dim": "#131317",
        "surface-container-lowest": "#0e0e12",
        "primary": "#c3c0ff",
        "outline": "#918fa1",
        "on-primary-fixed": "#0f0069",
        "surface-bright": "#39393d",
        "outline-variant": "#464555",
        "on-surface-variant": "#c7c4d8",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-fixed": "#351000",
        "on-primary-fixed-variant": "#3323cc",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        outfit: ["Outfit", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
